don't hide `checks done` section
ryantm/nixpkgs-update pull request #376
Opened 2023-12-17 04:05 UTC by zowoq

Sometimes reviewers don't expand this section so they don't see detail like this:

```
Warning: a test defined in `passthru.tests` did not pass
```

Reviews should also be waiting for ofborg to run the tests (which would likely also fail) but that isn't an issue that we can address at the moment.

2023-12-20 19:15 UTC, ryantm requested changes

2023-12-20 19:15 UTC, ryantm commented on src/Update.hs
We need to also delete the closing details tag and probably the summary tags too.

2023-12-20 22:33 UTC, zowoq commented on src/Update.hs
Done.

2023-12-21 01:36 UTC, ryantm approved these changes

2023-12-21 01:37 UTC, merged